import Head from "next/head";
import Styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Memes Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={Styles.mainGrid}>
          <div className={Styles.left}>
            <h1>The Rest API.</h1>
            <br />
            <p>
              The Rest API directly gets the best random memes from Reddit.
              Supports all programming languages.
            </p>
            <br />
            <h3>
              Check out the <button className={Styles.buttonLeft}>Docs</button>
            </h3>
          </div>
          <div>
            <h1 className={`center ${Styles.OR}`}>OR</h1>
          </div>
          <div className={Styles.right}>
            <h1>The NPM Package.</h1>
            <br />
            <p>
              The NPM package uses the Rest API to get the best memes. Only
              supports Javascript.
            </p>
            <br />
            <h3>
              Check out the <button className={Styles.buttonRight}>Docs</button>
            </h3>
          </div>
        </div>
      </main>
    </>
  );
}
